name: Deployment

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.KEY }}

          script: |
            cd /var/www/api.devstart.uz/public_html
            git clone git@github.com:parmonov98/devstart-api.git
            cd devstart-api
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
            php artisan optimize:clear
            php artisan optimize
            php artisan route:cache
